apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  forwardAuth:
    address: {{ .Values.auth.address }}
    tls:
      caOptional: true
      insecureSkipVerify: true
