apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: qmsauthn
spec:
  forwardAuth:
    address: {{ .Values.qmsauthn.address }}/oidc/profile
    tls:
      caOptional: true
      insecureSkipVerify: true